### ISSUE TITLE
docs: setup RTD

### ISSUE THREAD

**Issue by JaeAeich** [elixir-cloud-aai/tus-storagehandler#11]
`RTD` is either not set up for this repo or the link mentioned in the badge is wrong.

// @uniqueg

**Comment by uniqueg** [comment]
RTD wasn't set up.

Please add a note to the `README.md`. Perhaps group all the things that need to be done by an admin together, i.e.,:
- Defining GH Actions variables
- Set up RTD
- Any required or suggested repo configs?
- Anything else?

**Comment by JaeAeich** [comment]
Nope I think thats it, though the previous PR was merged without all the conversations being resolved, so I guess that should be added to PR rules. Apart from that everything seems peachy to me.
